# Generated by Django 6.0.1 on 2026-01-25 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('camps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.camp'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
