# Generated by Django 6.0.1 on 2026-03-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_advance_amount_booking_balance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
    ]
