# Generated by Django 6.0.1 on 2026-02-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='camps/cover/')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camps', to='accounts.organizerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CampImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camps/gallery/')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='camps.camp')),
            ],
        ),
        migrations.CreateModel(
            name='CampAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_slots', models.PositiveIntegerField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='camps.camp')),
            ],
            options={
                'unique_together': {('camp', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CampPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_per_person', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='camps.camp')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('camp', 'date')},
            },
        ),
    ]
