# Generated by Django 6.0.1 on 2026-01-22 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organizerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.PositiveIntegerField()),
                ('food_included', models.BooleanField()),
                ('activities', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISABLED', 'Disabled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camps', to='accounts.organizerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CampAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_slots', models.PositiveIntegerField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='camps.camp')),
            ],
            options={
                'unique_together': {('camp', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CampPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='camps.camp')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('camp', 'date')},
            },
        ),
    ]
