# Generated by Django 6.0.1 on 2026-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='food_included',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='organizer',
        ),
        migrations.AddField(
            model_name='camp',
            name='image',
            field=models.ImageField(default=12, upload_to='camps/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camp',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='camp',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='camp',
            name='price_per_person',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='camp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('disabled', 'Disabled')], max_length=20),
        ),
    ]
