# Generated by Django 6.0.1 on 2026-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='featured_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camp',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
