# Generated by Django 6.0.1 on 2026-01-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizerprofile'),
        ('camps', '0002_remove_camp_activities_remove_camp_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='image',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='camppricing',
            name='price',
        ),
        migrations.AddField(
            model_name='camp',
            name='cover_image',
            field=models.ImageField(default=12, upload_to='camps/cover/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camp',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='camps', to='accounts.organizerprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camppricing',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camppricing',
            name='price_per_person',
            field=models.PositiveIntegerField(default=0.08333333333333333),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='camppricing',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='camps.camp'),
        ),
        migrations.CreateModel(
            name='CampImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camps/gallery/')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='camps.camp')),
            ],
        ),
    ]
